version: '3.4'

services:
  isolutions.newbackproject.api:
    image: ${DOCKER_REGISTRY-}isolutionsnewbackprojectapi
    build:
      context: .
      dockerfile: src/ISolutions.NewBackProject.Api/Dockerfile

  isolutions.newbackproject.sso:
    image: ${DOCKER_REGISTRY-}isolutionsnewbackprojectsso
    build:
      context: .
      dockerfile: src/ISolutions.NewBackProject.SSO/Dockerfile
      
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Pass@word"
      MSSQL_PID: Express
    ports:
      - "1433:1433"